---
name: Test
on: workflow_call

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: npm ci
        working-directory: hello
      - run: npm run build

      - uses: ./
        with:
          version: pr/${{github.event.pull_request.number}}
